version: 2.1                #versi Schema CricleCI

jobs:
  lint-dockerfile:    # melakukan linting pada Dockerfile
    docker:
      - image: cimg/base:stable
    steps:
      - checkout              # Mendapatkan source code dari repository
      - run:                  # step Install Hadolint
          name: Install hadolint 
          command: |
            curl -sSL -o /tmp/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /tmp/hadolint
      - run:                  # Step untuk menjalankan hadolint terhadap Dockerfile
          name: Lint Dockerfile
          command: /tmp/hadolint Dockerfile   # Melakukan lint untuk memastikan Dockerfile sesuai standar 

  build-app-karsajobs-ui:         # Job kedua: build dan push image Docker untuk frontend karsajobs-ui
    docker:
      - image: cimg/node:16.20   # <<< SOLUSI UTAMA
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:                      # Build aplikasi frontend menggunakan Vue CLI
          name: Build Frontend
          command: npm run build
      - setup_remote_docker       # Mengaktifkan lingkungan Docker remote agar bisa melakukan build image
      - run:      
          name: Docker login      # Login ke DockerHub menggunakan environment variable CircleCI
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image    # Build image Docker untuk aplikasi frontend
          command: docker build -t $DOCKERHUB_USERNAME/karsajobs-ui:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image     # Push image Docker yang telah dibangun ke DockerHub
          command: docker push $DOCKERHUB_USERNAME/karsajobs-ui:$CIRCLE_SHA1

workflows:                  # Workflow mengatur urutan eksekusi job
  version: 2  
  ci-frontend:              # Nama workflow untuk frontend
    jobs:
      - lint-dockerfile:    # Job linting dijalankan terlebih dahulu
          filters:
            branches:
              only: karsajobs-ui    # Workflow hanya berjalan jika push dilakukan pada branch karsajobs-ui

      - build-app-karsajobs-ui:   # Job build UI dijalankan setelah lint-dockerfile sukses
          requires:
            - lint-dockerfile
          filters:
            branches:
              only: karsajobs-ui
